name: Linked issues
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      issues: read
      pull-requests: read
    steps:
      - id: issues
        uses: mondeja/pr-linked-issues-action@15e15b5aa999ae8a742117c9489aa63b1a007b76
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: join(steps.issues.outputs.issues) == ''
        run: exit 1
