name: Build and publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - develop
      - beta
      - stable

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PIP_USERNAME: ${{ secrets.PIP_USERNAME }}
      PIP_PASSWORD: ${{ secrets.PIP_PASSWORD }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python dependencies - watchdog_client
        working-directory: ./watchdog_client
        run: |
          uv pip install --system build hatchling
          uv pip install --system -e .
          uv pip install --system -e .[dev]
      - name: Build library
        working-directory: ./watchdog_client
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "Branch $BRANCH"
          export VERSION=$(bash ./scripts/calculate_version.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version $VERSION"
          bash ./scripts/build.sh
      - name: Publish to pip
        working-directory: ./watchdog_client
        run: |
          bash ./scripts/publish.sh
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build and publish container
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "Branch $BRANCH"
          export VERSION=$(bash ./scripts/calculate_version.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version $VERSION"
          export RELEASE=true
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          bash ./scripts/build_and_publish.sh
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
