name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install docker-compose and libs
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev build-essential
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install codecov pytest-cov
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Run unit tests
      run: |
        scripts/run_unit_tests.sh
    - name: Run comprehensive test
      run: |
        scripts/run_comprehensive_test.sh
    - name: Codecov
      run: |
        codecov -t $CODECOV_TOKEN
